### ISSUE TITLE
MP4 download contains streaming information

### ISSUE THREAD

**Issue by chillichicken** [dicer/auto-tatort#16]
Instead of downloading a mp4 video file the file contains streaming information:

    #EXTM3U
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=604000,RESOLUTION=512x288,CODECS="avc1.77.30, mp4a.40.2",CLOSED-CAPTIONS=NONE
    https://dasersteuni-vh.akamaihd.net/i/de/2018/01/06/ce71a409-4775-4d71-a903-3c48104831ec/,512-1,640-1,320-1,480-1,960-1,.mp4.csmil/index_0_av.m3u8?null=0
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1212000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2",CLOSED-CAPTIONS=NONE
    https://dasersteuni-vh.akamaihd.net/i/de/2018/01/06/ce71a409-4775-4d71-a903-3c48104831ec/,512-1,640-1,320-1,480-1,960-1,.mp4.csmil/index_1_av.m3u8?null=0
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=188000,RESOLUTION=320x180,CODECS="avc1.66.30, mp4a.40.2",CLOSED-CAPTIONS=NONE
    https://dasersteuni-vh.akamaihd.net/i/de/2018/01/06/ce71a409-4775-4d71-a903-3c48104831ec/,512-1,640-1,320-1,480-1,960-1,.mp4.csmil/index_2_av.m3u8?null=0
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=316000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2",CLOSED-CAPTIONS=NONE
    https://dasersteuni-vh.akamaihd.net/i/de/2018/01/06/ce71a409-4775-4d71-a903-3c48104831ec/,512-1,640-1,320-1,480-1,960-1,.mp4.csmil/index_3_av.m3u8?null=0
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1988000,RESOLUTION=960x540,CODECS="avc1.77.30, mp4a.40.2",CLOSED-CAPTIONS=NONE
    https://dasersteuni-vh.akamaihd.net/i/de/2018/01/06/ce71a409-4775-4d71-a903-3c48104831ec/,512-1,640-1,320-1,480-1,960-1,.mp4.csmil/index_4_av.m3u8?null=0

Reproduce like so:

    git clone git@github.com:dicer/auto-tatort.git
    cd auto-tatort/
    mv config.json.sample config.json
    python autoTatort.py

**Comment by dicer** [comment]
Problem was found and fixed. See commit above.
Reason was a change in Mediathek mid of December. Instead of selecting the highest quality,  the new quality "auto" was selected. This quality setting does not contain a mp4 download link but a m3u8 file for dynamic bitrate video players.
Subtitles were downloaded correctly so you should keep them.

Unfortunately as it seems not all videos can be saved :( Before you try a workaround below, make a backup of those files though! They contain valuable info you might be able to use. Here are two workarounds:

1. Get version 2.1.01 or newer, delete your downloadedItems.json and move the small .mp4 files out of your download directory. Let the new version run again and download some of the missing files (not all will be picked up as they might not be available anymore)

2. This workaround uses youtube-dl and assumes it is already installed. Move all the small mp4s into a separate directory. Use the following script in that directory to try and download the streams:
```for f in *.mp4; do mv "$f" "$f.m3u8" && grep -A1 '960x540' "$f.m3u8" | tail -1 | xargs youtube-dl -o "$f" ; done```
The script will rename the mp4s to .mp4.m3u8 and download the stream as .mp4. So if afterwards you have some .mp4.m3u8 without matching .mp4 file, the stream was probably not active anymore.

This should work for most Tatort. Only the first one this change occurred on is not downloadable anymore at the moment. Be quick as this will change soon. Sorry this happened! Should have caught it earlier :(
